### ISSUE TITLE
Recipe compile error if `node['ntp']['leapfile_from_mirror']` is false and `node['ntp']['leapfile_url']` is unset

### ISSUE THREAD

**Issue by zirkov** [sous-chefs/ntp#197]
## Actual
If the `leapfile_url` attribute is not set by a cookbook/policy depending on this cookbook (which is the default behaviour), it will still not use the predefined one but  try to use the attribute value (which is default to `nil`) and fail during compilation phase. 

## Expected 
If the `leapfile_url` attribute is not set by a cookbook/policy depending on this cookbook, keep the behaviour from previous versions

## Possible cause
https://github.com/chef-cookbooks/ntp/blob/4fc399dc3089b13198eb49a9d9e77424041e2679/recipes/default.rb#L86-L87
(`source` is duplicated)

## Example stack trace from test kitchen
```
         Chef::Exceptions::ValidationFailed
         ----------------------------------
         Property source must be one of: String, Array!  You passed nil.
         Cookbook Trace:
         ---------------
           /tmp/kitchen/cache/cookbooks/ntp/recipes/default.rb:87:in `block in from_file'
           /tmp/kitchen/cache/cookbooks/ntp/recipes/default.rb:82:in `from_file'
         Relevant File Content:
         ----------------------
         /tmp/kitchen/cache/cookbooks/ntp/recipes/default.rb:
          80:      end
          81:    else
          82:      cookbook_file node['ntp']['leapfile'] do
          83:        owner node['ntp']['conf_owner']
          84:        group node['ntp']['conf_group']
          85:        mode '0644'
          86:        source 'ntp.leapseconds'
          87>>       source node['ntp']['leapfile_url']
          88:        notifies :restart, "service[#{node['ntp']['service']}]"
          89:      end
          90:    end
          91:
          92:    include_recipe 'ntp::apparmor' if node['ntp']['apparmor_enabled']
          93:  end
          94:
          95:  if node['ntp']['listen'].nil? && !node['ntp']['listen_network'].nil?
          96:    if node['ntp']['listen_network'] == 'primary'
```

**Comment by damacus** [comment]
Closed via #198
